const ballotData = [
    { dates: "Oct. 13-14", sample: "1,000 RV", pollster: "Emerson College", sponsor: "-", dem: 44, gop: 43, type: "RV" },
    { dates: "Oct. 10-13", sample: "1,467 RV", pollster: "YouGov", sponsor: "The Economist", dem: 43, gop: 40, type: "RV" },
    { dates: "Oct. 8-12", sample: "1,000 A", pollster: "Hart Research Associates/Public Opinion Strategies", sponsor: "CNBC", dem: 48, gop: 47, type: "A" },
    { dates: "Oct. 7-8", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 48, gop: 45, type: "LV" },
    { dates: "Oct. 6-7", sample: "1,000 LV", pollster: "Quantus Insights", sponsor: "-", dem: 42, gop: 43, type: "LV" },
    { dates: "Oct. 4-6", sample: "1,490 RV", pollster: "YouGov", sponsor: "The Economist", dem: 44, gop: 39, type: "RV" },
    { dates: "Sep. 26-29", sample: "1,518 RV", pollster: "YouGov", sponsor: "The Economist", dem: 44, gop: 41, type: "RV" },
    { dates: "Sep. 25-29", sample: "1,126 RV", pollster: "YouGov", sponsor: "Yahoo News", dem: 44, gop: 40, type: "RV" },
    { dates: "Sep. 22-27", sample: "1,313 RV", pollster: "The New York Times/Siena College", sponsor: "-", dem: 47, gop: 45, type: "RV" },
    { dates: "Sep. 18-22", sample: "1,071 LV", pollster: "Echelon Insights", sponsor: "-", dem: 47, gop: 46, type: "LV" },
    { dates: "Sep. 19-22", sample: "1,392 RV", pollster: "YouGov", sponsor: "The Economist", dem: 45, gop: 42, type: "RV" },
    { dates: "Sep. 15-19", sample: "1,500 A", pollster: "Verasight", sponsor: "Strength In Numbers", dem: 47, gop: 42, type: "A" },
    { dates: "Sep. 15-18", sample: "1,541 RV", pollster: "The Argument/Verasight", sponsor: "-", dem: 53, gop: 47, type: "RV" },
    { dates: "Sep. 12-16", sample: "1,066 A", pollster: "AtlasIntel", sponsor: "-", dem: 52, gop: 44, type: "A" },
    { dates: "Sep. 12-15", sample: "1,420 RV", pollster: "YouGov", sponsor: "The Economist", dem: 43, gop: 41, type: "RV" },
    { dates: "Sep. 4-11", sample: "1,001 RV", pollster: "Clarity Campaign Labs", sponsor: "-", dem: 50, gop: 44, type: "RV" },
    { dates: "Sep. 5-8", sample: "1,487 RV", pollster: "YouGov", sponsor: "The Economist", dem: 44, gop: 40, type: "RV" },
    { dates: "Sep. 2-3", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 48, gop: 45, type: "LV" },
    { dates: "Aug. 29-Sep. 2", sample: "1,549 RV", pollster: "YouGov", sponsor: "The Economist", dem: 43, gop: 39, type: "RV" },
    { dates: "Aug. 21-Sep. 1", sample: "1,768 RV", pollster: "CNN/SSRS", sponsor: "-", dem: 52, gop: 48, type: "RV" },
    { dates: "Aug. 25-26", sample: "1,000 RV", pollster: "Emerson College", sponsor: "-", dem: 43, gop: 43, type: "RV" },
    { dates: "Aug. 22-25", sample: "1,377 RV", pollster: "YouGov", sponsor: "The Economist", dem: 43, gop: 41, type: "RV" },
    { dates: "Aug. 18-21", sample: "1,500 A", pollster: "Verasight", sponsor: "Strength In Numbers", dem: 49, gop: 41, type: "A" },
    { dates: "Aug. 14-18", sample: "1,057 LV", pollster: "Echelon Insights", sponsor: "-", dem: 47, gop: 46, type: "LV" },
    { dates: "Aug. 8-17", sample: "1,562 RV", pollster: "The Argument/Verasight", sponsor: "-", dem: 51, gop: 49, type: "RV" },
    { dates: "Aug. 11-13", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "-", dem: 45, gop: 42, type: "RV" },
    { dates: "Aug. 9-11", sample: "1,474 RV", pollster: "YouGov", sponsor: "The Economist", dem: 42, gop: 40, type: "RV" },
    { dates: "Aug. 7-9", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 47, gop: 46, type: "LV" },
    { dates: "Aug. 1-4", sample: "1,528 RV", pollster: "YouGov", sponsor: "The Economist", dem: 44, gop: 38, type: "RV" },
    { dates: "Jul. 29-Aug. 3", sample: "1,000 A", pollster: "Hart Research Associates/Public Opinion Strategies", sponsor: "CNBC", dem: 49, gop: 44, type: "A" },
    { dates: "Jul. 24-31", sample: "1,018 RV", pollster: "Clarity Campaign Labs", sponsor: "-", dem: 51, gop: 43, type: "RV" },
    { dates: "Jul. 25-28", sample: "1,610 RV", pollster: "YouGov", sponsor: "The Economist", dem: 43, gop: 41, type: "RV" },
    { dates: "Jul. 24-28", sample: "1,167 RV", pollster: "YouGov", sponsor: "Yahoo News", dem: 46, gop: 39, type: "RV" },
    { dates: "Jul. 21-22", sample: "1,400 RV", pollster: "Emerson College", sponsor: "Nexstar", dem: 44, gop: 42, type: "RV" },
    { dates: "Jul. 13-18", sample: "1,435 A", pollster: "AtlasIntel", sponsor: "-", dem: 51, gop: 43, type: "A" },
    { dates: "Jul. 14-16", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "-", dem: 44, gop: 42, type: "RV" },
    { dates: "Jul. 14-16", sample: "1,500 A", pollster: "Verasight", sponsor: "Strength In Numbers", dem: 47, gop: 43, type: "A" },
    { dates: "Jul. 12-14", sample: "3,022 RV", pollster: "Big Data Poll", sponsor: "-", dem: 42, gop: 41, type: "RV" },
    { dates: "Jul. 10-14", sample: "1,084 LV", pollster: "Echelon Insights", sponsor: "-", dem: 48, gop: 47, type: "LV" },
    { dates: "Jul. 1-2", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 47, gop: 46, type: "LV" },
    { dates: "Jun. 24-25", sample: "1,000 RV", pollster: "Emerson College", sponsor: "-", dem: 43, gop: 40, type: "RV" },
    { dates: "Jun. 23-25", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "-", dem: 43, gop: 42, type: "RV" },
    { dates: "Jun. 19-21", sample: "800 LV", pollster: "Cygnal", sponsor: "-", dem: 48, gop: 46, type: "LV" },
    { dates: "Jun. 17-18", sample: "1,002 LV", pollster: "Echelon Insights", sponsor: "-", dem: 47, gop: 48, type: "LV" },
    { dates: "Jun. 12-17", sample: "982 LV", pollster: "Echelon Insights", sponsor: "-", dem: 47, gop: 48, type: "LV" },
    { dates: "Jun. 12-16", sample: "1,035 LV", pollster: "co/efficient", sponsor: "-", dem: 46, gop: 46, type: "LV" },
    { dates: "Jun. 5-14", sample: "1,000 RV", pollster: "Clarity Campaign Labs", sponsor: "-", dem: 50, gop: 45, type: "RV" },
    { dates: "Jun. 6-12", sample: "1,500 A", pollster: "Verasight", sponsor: "Strength in Numbers", dem: 45, gop: 37, type: "A" },
    { dates: "Jun. 9-11", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "TrendingPolitics", dem: 43, gop: 43, type: "RV" },
    { dates: "Jun. 6", sample: "1,006 RV", pollster: "J.L. Partners", sponsor: "DailyMail.com", dem: 42, gop: 35, type: "RV" },
    { dates: "Jun. 1-4", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "TrendingPolitics", dem: 46, gop: 45, type: "RV" },
    { dates: "Jun. 3-4", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 47, gop: 47, type: "LV" },
    { dates: "May. 30-Jun. 2", sample: "1,436 RV", pollster: "YouGov", sponsor: "The Economist", dem: 44, gop: 42, type: "RV" },
    { dates: "May. 21-27", sample: "3,469 RV", pollster: "AtlasIntel", sponsor: "-", dem: 51, gop: 42, type: "RV" },
    { dates: "May. 15-19", sample: "800 RV", pollster: "Fabrizio Ward", sponsor: "Pinpoint Policy Institute", dem: 42, gop: 42, type: "RV" },
    { dates: "May. 8-12", sample: "1,000 LV", pollster: "Echelon Insights", sponsor: "-", dem: 47, gop: 48, type: "LV" },
    { dates: "May. 7-9", sample: "1,462 LV", pollster: "co/efficient", sponsor: "-", dem: 45, gop: 42, type: "LV" },
    { dates: "May. 6-8", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 47, gop: 47, type: "LV" },
    { dates: "May. 5-7", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "TrendingPolitics", dem: 45, gop: 45, type: "RV" },
    { dates: "May. 1-6", sample: "1,000 A", pollster: "Verasight", sponsor: "Strength in Numbers", dem: 47, gop: 41, type: "A" },
    { dates: "May. 3-5", sample: "3,128 RV", pollster: "Big Data Poll", sponsor: "Public Polling Project", dem: 40, gop: 42, type: "RV" },
    { dates: "Apr. 21-24", sample: "913 RV", pollster: "The New York Times/Siena College", sponsor: "-", dem: 47, gop: 44, type: "RV" },
    { dates: "Apr. 18-21", sample: "1,104 RV", pollster: "Beacon Research/Shaw & Co. Research", sponsor: "Fox News", dem: 49, gop: 42, type: "RV" },
    { dates: "Apr. 10-14", sample: "1,014 LV", pollster: "Echelon Insights", sponsor: "-", dem: 47, gop: 47, type: "LV" },
    { dates: "Apr. 9-14", sample: "1,008 RV", pollster: "Clarity Campaign Labs", sponsor: "-", dem: 44, gop: 45, type: "RV" },
    { dates: "Apr. 9-13", sample: "1,000 A", pollster: "Hart Research Associates/Public Opinion Strategies", sponsor: "CNBC", dem: 48, gop: 46, type: "A" },
    { dates: "Apr. 5-8", sample: "1,558 RV", pollster: "YouGov", sponsor: "The Economist", dem: 43, gop: 42, type: "RV" },
    { dates: "Apr. 1-3", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 48, gop: 47, type: "LV" },
    { dates: "Mar. 25-27", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "-", dem: 45, gop: 46, type: "RV" },
    { dates: "Mar. 10-13", sample: "1,007 LV", pollster: "Echelon Insights", sponsor: "-", dem: 46, gop: 47, type: "LV" },
    { dates: "Mar. 7-11", sample: "1,000 RV", pollster: "Hart Research Associates/Public Opinion Strategies", sponsor: "NBC News", dem: 48, gop: 47, type: "RV" },
    { dates: "Mar. 3-9", sample: "1,036 RV", pollster: "Clarity Campaign Labs", sponsor: "-", dem: 46, gop: 44, type: "RV" },
    { dates: "Mar. 3-5", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 47, gop: 46, type: "LV" },
    { dates: "Mar. 2-3", sample: "1,000 RV", pollster: "Emerson College", sponsor: "-", dem: 44, gop: 41, type: "RV" },
    { dates: "Feb. 25-Mar. 2", sample: "1,000 RV", pollster: "Public Opinion Strategies", sponsor: "Paragon Health Institute", dem: 44, gop: 46, type: "RV" },
    { dates: "Feb. 16-18", sample: "1,451 RV", pollster: "YouGov", sponsor: "The Economist", dem: 42, gop: 41, type: "RV" },
    { dates: "Feb. 15-17", sample: "2,063 LV", pollster: "co/efficient", sponsor: "-", dem: 44, gop: 46, type: "LV" },
    { dates: "Feb. 10-13", sample: "1,010 LV", pollster: "Echelon Insights", sponsor: "-", dem: 46, gop: 47, type: "LV" },
    { dates: "Feb. 10-12", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "TrendingPolitics", dem: 44, gop: 48, type: "RV" },
    { dates: "Jan. 31-Feb. 6", sample: "1,102 RV", pollster: "Clarity Campaign Labs", sponsor: "-", dem: 45, gop: 44, type: "RV" },
    { dates: "Feb. 4-5", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 46, gop: 47, type: "LV" },
    { dates: "Jan. 22-23", sample: "1,000 RV", pollster: "Quantus Insights", sponsor: "TrendingPolitics", dem: 45, gop: 48, type: "RV" },
    { dates: "Jan. 9-12", sample: "1,500 LV", pollster: "Cygnal", sponsor: "-", dem: 45, gop: 47, type: "LV" }
];

// Export to window
window.ballotData = ballotData;
